# Generated by Django 3.2.3 on 2023-06-12 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_tagrecipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagrecipe',
            options={'verbose_name': 'Тег и рецепт', 'verbose_name_plural': 'Теги и рецепты'},
        ),
    ]
