# Generated by Django 3.2.3 on 2023-06-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_tagrecipe_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='number',
            new_name='amount',
        ),
    ]
